### ISSUE TITLE
"panic: runtime error: index out of range" on app upgrade

### ISSUE THREAD

**Issue by relan** [mvdan/fdroidcl#18]
On each app upgrade I get this error:

```
$ fdroidcl upgrade com.nutomic.syncthingandroid
Downloading http://f-droid.org/repo/com.nutomic.syncthingandroid_103.apk... done
Upgrading com.nutomic.syncthingandroid... panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x8147a0, 0xc82000e100)
    /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
github.com/mvdan/fdroidcl/adb.getFailureCode(0xc820082320, 0x0, 0x0, 0x0, 0x0)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/adb/device.go:117 +0x78
github.com/mvdan/fdroidcl/adb.(*Device).install(0xc8200c2770, 0xc820e47a98, 0x1, 0x1, 0xc820a59860, 0x45, 0x0, 0x0)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/adb/device.go:157 +0x2b1
github.com/mvdan/fdroidcl/adb.(*Device).Upgrade(0xc8200c2770, 0xc820a59860, 0x45, 0x0, 0x0)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/adb/device.go:165 +0x94
main.upgradeApk(0xc8200c2770, 0xc820940000, 0xc820a59860, 0x45)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/cmd/fdroidcl/upgrade.go:48 +0x143
main.downloadAndDo(0xc82002a000, 0x1, 0x1, 0xc8200c2770, 0x95b4b8)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/cmd/fdroidcl/install.go:53 +0x37d
main.runUpgrade(0xc82000a3e0, 0x1, 0x1)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/cmd/fdroidcl/upgrade.go:43 +0x522
main.main()
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/cmd/fdroidcl/main.go:180 +0x3fb
```

App is actually upgraded. This may be related to the adb version (Platform-tools 24.0.3):

```
Android Debug Bridge version 1.0.36
Revision e02fe72a18c3-android
```

Target device is Nexus 9, Android 7.0 (NRD90R). Host is Fedora 24 x86-64. I use adb from the official SDK, not from Fedora repositories. fdroidcl from master @ 4d0eeea.

**Comment by relan** [comment]
The problem here is that `adb install` now prints `Success` to stderr. So this patch fixes the issue (but does not care about compatibility):

```patch
diff --git a/adb/device.go b/adb/device.go
index a439ed4..7bd3c4a 100644
--- a/adb/device.go
+++ b/adb/device.go
@@ -143,14 +143,14 @@ func withOpts(cmd string, opts []string, args ...string) []string {
 
 func (d *Device) install(opts []string, path string) error {
 	cmd := d.AdbCmd(withOpts("install", opts, path)...)
-	stdout, err := cmd.StdoutPipe()
+	stderr, err := cmd.StderrPipe()
 	if err != nil {
 		return err
 	}
 	if err := cmd.Start(); err != nil {
 		return err
 	}
-	line := getResultLine(stdout)
+	line := getResultLine(stderr)
 	if line == "Success" {
 		return nil
 	}
```

Note that `adb uninstall` still prints `Success` to stdout. Crazy.

**Comment by mvdan** [comment]
The solution then is probably to catch both stdout and stderr.

**Comment by mvdan** [comment]
What platform was this on? I'm using 24.0.3 on linux amd64 and I was unable to reproduce the crash.

**Comment by mvdan** [comment]
Also:

```
 $ adb version
Android Debug Bridge version 1.0.36
Revision e02fe72a18c3-android
```

**Comment by relan** [comment]
> What platform was this on?

Linux (Fedora 24), amd64. Adb is exactly the same version as yours.

**Comment by mvdan** [comment]
The solution here would be to use https://golang.org/pkg/os/exec/#Cmd.CombinedOutput instead of an stdout pipe.

@relan since you can reproduce the issue, care to come up with a patch? Otherwise I'll provide one in a few days and ask you to test it out.
