### ISSUE TITLE
Update apps - Ignore a list of app id and proceed with installation of other apps when there is an error

### ISSUE THREAD

**Issue by lamyergeier** [mvdan/fdroidcl#76]
I am trying to install updates for all apps. Firstly, all updates are downloaded, and the update stops and skips installation of all apps, if it could not proceed with a particular app. May be it should skip the problematic app. Finally, is there a way to save a file that contains a list of app id that should be skipped. This is bacause some of the apps, I installed manually from github and other sources, and because of it the update doesn't happen.  Please see below for the example:

```bash
$ fdroidcl search -u
fdroidcl install -u
chat.rocket.android              Rocket.Chat - 4.40.0 (47250) -> 4.43.0 (52296)
    Team Communication Tool
com.bnyro.contacts               Connect You - 6.0 (23) -> 8.1 (27)
    Privacy focused contacts and SMS messenger app build with MD3
com.bnyro.translate              Translate You - 7.0 (37) -> 8.0 (39)
    Privacy focused translator app built with MD3
com.brouken.player               Just (Video) Player - 0.147 (147) -> 0.154 (154)
    Simple video player based on ExoPlayer library
com.foobnix.pro.pdf.reader       Librera Reader - 8.9.105-fdroid (5846) -> 8.9.115-fdroid (5850)
    Book and PDF reader
com.github.ashutoshgngwr.noice   Noice: Natural calming noise - 2.4.0 (62) -> 2.5.4 (69)
    Focus, meditate and relax with natural calming noise.
com.google.android.stardroid     Sky Map - 1.10.0 - RC3 (1532) -> 1.10.1 - RC1 (1541)
    Sky Map to explore the skies
com.jens.automation2             Automation - 1.7.7 (122) -> 1.7.19 (136)
    Automate stuff on your device by creating rules.
com.zulipmobile                  Zulip - 27.208 (208) -> 27.221 (221)
    The Zulip mobile app, chat for distributed teams
eu.faircode.email                FairEmail - 1.2134 (2134) -> 1.2139 (2139)
    Fully featured email client. Neat, intuitive user interface. Privacy friendly
io.timelimit.android.aosp.direct TimeLimit.io - 6.7.0 (193) -> 6.17.0 (211)
    Flexibly limit the usage duration
org.telegram.messenger           Telegram FOSS - 10.3.2 (41452) -> 10.3.2 (41459)
    Telegram is a messaging app with a focus on speed and security.
org.totschnig.myexpenses         My Expenses - 3.3.7.2 (517) -> 3.6.9 (678)
    Easy to use personal finance manager: rich functionality and Open Source
https://f-droid.org/repo/chat.rocket.android_52296.apk 100% |█████████████████████████████| (33/33 MB, 7.7 MB/s) [4s:0s]
https://f-droid.org/repo/com.bnyro.contacts_27.apk 100% |███████████████████████████████| (2.5/2.5 MB, 7.4 MB/s) [0s:0s]
https://f-droid.org/repo/com.bnyro.translate_39.apk 100% |████████████████████████████████| (15/15 MB, 7.9 MB/s) [1s:0s]
https://f-droid.org/repo/com.brouken.player_154.apk 100% |████████████████████████████████| (70/70 MB, 8.6 MB/s) [8s:0s]
https://f-droid.org/repo/com.foobnix.pro.pdf.reader_5850.apk 100% |███████████████████████| (63/63 MB, 8.3 MB/s) [7s:0s]
https://f-droid.org/repo/com.github.ashutoshgngwr.noice_69.apk 100% |███████████████████| (4.7/4.7 MB, 9.2 MB/s) [0s:0s]
https://f-droid.org/repo/com.google.android.stardroid_1541.apk 100% |███████████████████| (3.8/3.8 MB, 7.6 MB/s) [0s:0s]
https://f-droid.org/repo/com.jens.automation2_136.apk 100% |████████████████████████████| (5.4/5.4 MB, 5.6 MB/s) [0s:0s]
https://f-droid.org/repo/com.zulipmobile_221.apk 100% |████████████████████████████████| (115/115 MB, 7.8 MB/s) [14s:0s]
https://f-droid.org/repo/eu.faircode.email_2139.apk 100% |████████████████████████████████| (26/26 MB, 8.7 MB/s) [2s:0s]
https://f-droid.org/repo/io.timelimit.android.aosp.direct_211.apk 100% |████████████████| (6.2/6.2 MB, 9.2 MB/s) [0s:0s]
https://f-droid.org/repo/org.telegram.messenger_41459.apk 100% |██████████████████████████| (75/75 MB, 9.3 MB/s) [7s:0s]
https://f-droid.org/repo/org.totschnig.myexpenses_678.apk 100% |██████████████████████████| (25/25 MB, 7.1 MB/s) [3s:0s]
Installing chat.rocket.android
install: could not install chat.rocket.android: exit status 1: unknown error: FAILED_UPDATE_INCOMPATIBLE: Existing package chat.rocket.android signatures do not match newer version; ignoring!
```

**Comment by Linus789** [comment]
Take a look at `fdroidcl install --help`.

> May be it should skip the problematic app.

`fdroidcl install -u -s`

> Finally, is there a way to save a file that contains a list of app id that should be skipped.

`fdroidcl install -u -e "$(cat skip.txt)"`

**Comment by lamyergeier** [comment]
@Linus789 

We can observe in the following that the installation stopped in the middle due to some error. Could it continue to the next app?

```
$ fdroidcl install -u -s
https://f-droid.org/repo/chat.rocket.android_52296.apk not modified
https://f-droid.org/repo/com.bnyro.contacts_27.apk not modified
https://f-droid.org/repo/com.bnyro.translate_39.apk not modified
https://f-droid.org/repo/com.brouken.player_154.apk not modified
https://f-droid.org/repo/com.github.ashutoshgngwr.noice_69.apk not modified
https://f-droid.org/repo/com.google.android.stardroid_1541.apk not modified
https://f-droid.org/repo/com.jens.automation2_136.apk not modified
https://f-droid.org/repo/com.zulipmobile_221.apk not modified
https://f-droid.org/repo/eu.faircode.email_2139.apk not modified
https://f-droid.org/repo/io.timelimit.android.aosp.direct_211.apk not modified
https://f-droid.org/repo/org.telegram.messenger_41459.apk not modified
https://f-droid.org/repo/org.totschnig.myexpenses_678.apk not modified
Installing chat.rocket.android
Installing chat.rocket.android failed, skipping...
Installing com.bnyro.contacts
Installing com.bnyro.contacts failed, skipping...
Installing com.bnyro.translate
Installing com.bnyro.translate failed, skipping...
Installing com.brouken.player
Installing com.brouken.player failed, skipping...
Installing com.github.ashutoshgngwr.noice
Installing com.github.ashutoshgngwr.noice failed, skipping...
Installing com.google.android.stardroid
Installing com.google.android.stardroid failed, skipping...
Installing com.jens.automation2
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
mvdan.cc/fdroidcl/adb.getFailureCode(...)
	mvdan.cc/fdroidcl/adb/device.go:145
mvdan.cc/fdroidcl/adb.(*Device).InstallUser(0xc0001ec690, {0xc005886100, 0x3c}, {0xc00329e79a, 0x3})
	mvdan.cc/fdroidcl/adb/device.go:188 +0x3b8
main.installApk(0x701de0?, 0xc000d86780, 0xc0001f9158, {0xc005886100, 0x3c})
	mvdan.cc/fdroidcl/install.go:258 +0x255
main.downloadAndDo({0xc0032ae000?, 0xc, 0xb1?}, 0x19?, 0x199?)
	mvdan.cc/fdroidcl/install.go:227 +0x58e
main.runInstall({0xc0000160b0, 0x0, 0x0})
	mvdan.cc/fdroidcl/install.go:119 +0x6db
main.main1()
	mvdan.cc/fdroidcl/main.go:226 +0x3da
main.main()
	mvdan.cc/fdroidcl/main.go:193 +0x19
```

**Comment by Linus789** [comment]
Could you manually download com.jens.automation2 from F-Droid and install it via `adb install -r <automation.apk>` and show me the output?
